# SPDX-FileCopyrightText: 2024 Dominik Wombacher <dominik@wombacher.cc>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fluent-bit-syslog-to-aws-cloudtrail-data.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fluent-bit-syslog-to-aws-cloudtrail-data.labels" . | nindent 4 }}
data:
  fluent-bit.conf: |
    [SERVICE]
      # Flush
      # =====
      # set an interval of seconds before to flush records to a destination
      flush        1

      # Daemon
      # ======
      # instruct Fluent Bit to run in foreground or background mode.
      daemon       Off

      # Log_Level
      # =========
      # Set the verbosity level of the service, values can be:
      #
      # - error
      # - warning
      # - info
      # - debug
      # - trace
      #
      # by default 'info' is set, that means it includes 'error' and 'warning'.
      log_level    info

      # Parsers File
      # ============
      # specify an optional 'Parsers' configuration file
      parsers_file /fluent-bit/etc/parsers.conf

      # Plugins File
      # ============
      # specify an optional 'Plugins' configuration file to load external plugins.
      plugins_file /fluent-bit/etc/plugins.conf

      # HTTP Server
      # ===========
      # Enable/Disable the built-in HTTP Server for metrics
      # - https://docs.fluentbit.io/manual/administration/monitoring
      http_server  Off
      http_listen  0.0.0.0
      http_port    2020

      # Storage
      # =======
      # publish storage pipeline metrics in '/api/v1/storage'. The metrics are
      # exported only if the 'http_server' option is enabled.
      # - https://docs.fluentbit.io/manual/administration/buffering-and-storage
      storage.metrics on

    @INCLUDE input-syslog.conf
    @INCLUDE output-aws-cloudtrail-data.conf
    {{- if .Values.enableStandardOutput }}
    @INCLUDE output-stdout.conf
    {{- end }}
  plugins.conf: |
    [PLUGINS]
      Path /fluent-bit/aws-cloudtrail-data.so
  input-syslog.conf: |
    [INPUT]
      Name     syslog
      Parser   syslog-rfc3164
      Listen   0.0.0.0
      Port     5140
      Mode     tcp
  output-stdout.conf: |
    [OUTPUT]
        Name  stdout
        Match *
  aws-cloudtrail-data.conf: |
    [OUTPUT]
        Name  aws-cloudtrail-data
