# SPDX-FileCopyrightText: 2024 Dominik Wombacher <dominik@wombacher.cc>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fluent-bit-syslog-to-aws-cloudtrail-data.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "fluent-bit-syslog-to-aws-cloudtrail-data.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "fluent-bit-syslog-to-aws-cloudtrail-data.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fluent-bit-syslog-to-aws-cloudtrail-data.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fluent-bit-syslog-to-aws-cloudtrail-data.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /fluent-bit/bin/fluent-bit
          args:
            - -i syslog
            - -o aws-cloudtrail-data
          env:
            - name: AWS_CLOUDTRAIL_DATA_CHANNELARN
              value: {{ .Values.channelArn }}
          ports:
            - name: syslog
              containerPort: {{ .Values.service.syslog.port }}
              protocol: TCP
            - name: http
              containerPort: {{ .Values.service.monitoring.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            - name: "configmap-{{ include "fluent-bit-syslog-to-aws-cloudtrail-data.fullname" . }}"
              mountPath: /etc/fluent-bit
              readOnly: true
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        - name: "configmap-{{ include "fluent-bit-syslog-to-aws-cloudtrail-data.fullname" . }}"
          configMap:
            name: {{ include "fluent-bit-syslog-to-aws-cloudtrail-data.fullname" . }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
