# SPDX-FileCopyrightText: 2024 Dominik Wombacher <dominik@wombacher.cc>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ include "fluent-bit-syslog-to-aws-cloudtrail-data.fullname" . }}-syslog
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "fluent-bit-syslog-to-aws-cloudtrail-data.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.syslog.type }}
  ports:
    - port: {{ .Values.service.syslog.port }}
      targetPort: 5140
      protocol: TCP
      name: syslog
  selector:
    {{- include "fluent-bit-syslog-to-aws-cloudtrail-data.selectorLabels" . | nindent 4 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "fluent-bit-syslog-to-aws-cloudtrail-data.fullname" . }}-monitoring
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "fluent-bit-syslog-to-aws-cloudtrail-data.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.monitoring.type }}
  ports:
    - port: {{ .Values.service.monitoring.port }}
      targetPort: 2020
      protocol: TCP
      name: http
  selector:
    {{- include "fluent-bit-syslog-to-aws-cloudtrail-data.selectorLabels" . | nindent 4 }}
